version: 2.1

orbs:
  node: circleci/node@4.2.1
  heroku: circleci/heroku@0.0.10

jobs:
  build_deploy_stg:
    executor:
      name: node/default
      tag: '12.19.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
